#!/bin/bash

# Making files executable
echo "Making lpull and lupdate executable files ..."
chmod +x lpull
chmod +x lupdate

# Moving files to prefered executable location
echo "Moving files to prefered executables location: '/usr/local/bin/' ..."
sudo cp ./lpull /usr/local/bin/lpull
sudo cp ./lupdate /usr/local/bin/lupdate

echo "Setup finshed!"
echo "Start a new terminal session for changes to be applied"
